# Generated by Django 3.0.5 on 2020-07-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('mainApp', '0003_fase_tamañoitem_tiposdefecto_tiposparte'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDefecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encontrado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha encontrado')),
                ('fecha_removido', models.DateTimeField(blank=True, null=True, verbose_name='Fecha removido')),
                ('tiempo_arreglo', models.IntegerField(verbose_name='Tiempo duracion de arreglo')),
                ('id_fase_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainapps_fases_related_creacion', to='mainApp.Fase', verbose_name='Fase creación')),
                ('id_fase_eliminacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainapps_fases_related_finalizacion', to='mainApp.Fase', verbose_name='Fase eliminación')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='proyecto')),
                ('id_tipo_defecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.TiposDefecto', verbose_name='Defecto')),
            ],
            options={
                'verbose_name': 'Registro de defecto',
                'verbose_name_plural': 'Registro de defectos',
                'ordering': ['id_tipo_defecto', 'fecha_encontrado'],
            },
        ),
    ]
