# Generated by Django 3.0.5 on 2020-07-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiposDefectos', '0001_initial'),
        ('registroDefectos', '0002_auto_20200728_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodefecto',
            name='id_tipo_defecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiposDefectos.TiposDefecto', verbose_name='Defecto'),
        ),
    ]
