# Generated by Django 3.0.5 on 2020-05-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='planned',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo planeado'),
        ),
    ]
