# Generated by Django 3.0.5 on 2020-05-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200507_1747'),
        ('modules', '0002_auto_20200509_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='proyecto'),
        ),
    ]
