# Generated by Django 3.0.5 on 2020-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fase', models.CharField(max_length=50, verbose_name='fase')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True, verbose_name='fechaCreacion')),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
