# Generated by Django 3.0.5 on 2020-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
