# Generated by Django 3.0.5 on 2020-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_proceso_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='numero',
            field=models.FloatField(verbose_name='Numero psp'),
        ),
    ]
