# Generated by Django 3.0.5 on 2020-07-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('partesGenerales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartesReusada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(verbose_name='Tamaño planeado')),
                ('actual', models.IntegerField(verbose_name='Tamaño actual')),
                ('id_parte_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partesGenerales.PartesGeneral', verbose_name='Parte General')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Parte Reusada',
                'verbose_name_plural': 'Partes Reusadas',
                'ordering': ['plan'],
            },
        ),
    ]
