# Generated by Django 3.0.5 on 2020-07-25 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0003_fase_tamañoitem_tiposdefecto_tiposparte'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('interrupciones', models.IntegerField(verbose_name='Interrupciones')),
                ('fecha_final', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('tiempo_total', models.IntegerField(verbose_name='Timpo tota(Delta)')),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Fase', verbose_name='Fase')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'Registro de tiempo',
                'verbose_name_plural': 'Registro de tiempos',
                'ordering': ['fecha_inicio', 'tiempo_total'],
            },
        ),
    ]
