# Generated by Django 3.0.5 on 2020-07-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0002_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True, verbose_name='fechaCreacion')),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Proceso', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
