# Generated by Django 3.0.5 on 2020-07-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_semana', models.DateField(verbose_name='Fecha de semana')),
                ('horas_acomuladas_actual', models.IntegerField(verbose_name='Horas acomuladas actual')),
                ('horas_acomuladas_plan', models.IntegerField(verbose_name='Horas acomuladas plan')),
                ('horas_actual', models.IntegerField(verbose_name='Horas actual')),
                ('ev_acomuladas_actual', models.CharField(max_length=50, verbose_name='Ev acomuladas actual')),
                ('num_semana', models.IntegerField(verbose_name='Numero de semana')),
                ('ev_pedicted', models.CharField(max_length=50, verbose_name='Ev predicted')),
                ('horas_plan', models.IntegerField(verbose_name='Horas plan')),
                ('ev_acomulativo_predited', models.CharField(max_length=50, verbose_name='Ev acomulativo proyecto')),
                ('pv_acomulados_pla', models.CharField(max_length=50, verbose_name='Pv acomulados plan')),
                ('valor_actual', models.CharField(max_length=50, verbose_name='Valor actual')),
                ('valor_plan', models.CharField(max_length=50, verbose_name='Valor plan')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
                'ordering': ['fecha_semana'],
            },
        ),
    ]
