# Generated by Django 3.0.5 on 2020-06-12 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de inicio')),
                ('interruption', models.IntegerField(blank=True, null=True, verbose_name='Interrupciones')),
                ('stopDate', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de fin')),
                ('delta', models.IntegerField(blank=True, null=True, verbose_name='Tiempo min')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phases.Phase', verbose_name='Fase')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Registro de tiempo',
                'verbose_name_plural': 'Registro de tiempos',
                'ordering': ['startDate'],
            },
        ),
    ]
