# Generated by Django 3.0.5 on 2020-07-30 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profesores', '0003_auto_20200730_1832'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='rol',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_estudiante', to='profesores.Profesor', verbose_name='profesor'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
