# Generated by Django 3.0.5 on 2020-07-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('objetivos', models.TextField(verbose_name='Objetivos')),
                ('condiciones', models.TextField(verbose_name='Condiciones')),
                ('resultados_esperados', models.TextField(verbose_name='Resultados Esperados')),
                ('numero_test', models.IntegerField(verbose_name='Numero de test')),
                ('resultados_actules', models.TextField(verbose_name='Resultados Actules')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['nombre', 'numero_test'],
            },
        ),
    ]
