# Generated by Django 3.0.5 on 2020-07-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('partesGenerales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartesBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseplan', models.IntegerField(verbose_name='Planeado base')),
                ('planDel', models.IntegerField(verbose_name='Planeado a eliminar')),
                ('planMod', models.IntegerField(verbose_name='Planeado a modificar')),
                ('planAdd', models.IntegerField(verbose_name='Planeado a añadir')),
                ('actualBase', models.IntegerField(verbose_name='Actual base')),
                ('actualDel', models.IntegerField(verbose_name='Actual a eliminar')),
                ('actualMod', models.IntegerField(verbose_name='Actual a modificar')),
                ('actualAdd', models.IntegerField(verbose_name='Actual a añadir')),
                ('id_parte_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partesGenerales.PartesGeneral', verbose_name='Parte General')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Parte Base',
                'verbose_name_plural': 'Partes Bases',
                'ordering': ['baseplan'],
            },
        ),
    ]
