# Generated by Django 3.0.5 on 2020-07-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('solucion', models.TextField(verbose_name='Solucion')),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pip',
                'verbose_name_plural': 'Pips',
            },
        ),
    ]
