# Generated by Django 3.0.5 on 2020-07-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartesGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('medida_tamaño', models.CharField(max_length=50, verbose_name='Medida de tamaño')),
                ('tipo_contabilidad', models.CharField(max_length=50, verbose_name='Tipo de contabilidad')),
                ('tipo_parte', models.CharField(max_length=50, verbose_name='Tipo de parte')),
                ('tamaño_actual', models.IntegerField(verbose_name='Tamaño actual')),
                ('nombre_contenedor', models.CharField(max_length=50, verbose_name='Nombre de contenedor')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'Parte General',
                'verbose_name_plural': 'Partes Generales',
                'ordering': ['nombre'],
            },
        ),
    ]
